### ISSUE TITLE
CCSprite Normal blending property not saved

### ISSUE THREAD

**Issue by plungeint** [cocos2d/CocosBuilder#157] opened 2012-10-22 14:47 UTC
Just open a scene, add a CCSprite, and change its blending properties using the "Normal" button. Then save the scene, quit cocosbuilder and open it again: the blending property is not the one that was supposed to be saved.

**Comment by mikey0000** [comment] 2012-11-20 23:22
seconded, keeps defaulting all sprites to blend src Alpa and blend dst One - Src Alpha

**Comment by maxrossi** [comment] 2012-12-20 11:38
Yes, this is very annoying

**Comment by wischie** [comment] 2012-12-26 19:30
This started to happen to me today as well, so annoying, going to try to save the scene and start cocos builder fresh, possibly try going to build 3 alpha?

ugh!

edit:
it appears that cocos builder and premultiplied alpha for pvr.ccz's is a bit weird. i've been using texture packer and exporting pvr.ccz's with pre-multipied alpha, cocos builder automatically sets the blend src to Src Alpha instead of One, even though One is what shows up in blend src when you hit normal for the blending mode.

i've worked around this issue (haven't tested on a device yet) but now i just disable pre-multiplied alpha for the texture sheets, and because cocos builder changes back to src alpha for the blend src, now the images look correct. i think cocos builder is automatically assuming that you aren't using pre-multiplied alpha, but the issue is very strange and only snaps like this when you set the blend src to one and the blend dst to one-src alpha.

someone please help me understand this weird glitch?!

**Comment by vlidholt** [comment] 2013-01-23 00:09
I think that this is fixed in CocosBuilder 3, please reopen if problem still is there, and if possible provide a test case.

**Closed as completed by vlidholt** 2013-01-23 00:09 UTC
Labels: bug

**Comment by huangyuching** [comment] 2013-03-06 06:43
The problem is still in the latest commit. All blending properties which are One, One-Src Alpha will be saved as Src Alpha, One-Src Alpha.
